name: "Build and publish latest images"

on:
  workflow_call:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-publish-latest:
    name: "Build and publish latest and ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Log in to Docker"
        id: login-to-docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build images"
        id: build-docker-images
        run: |
          version_label=$GITHUB_REF_NAME-$(date '+%Y%m%d')
          docker build --file "$GITHUB_WORKSPACE/Dockerfile.ubuntu" --target steamcmd --tag nwsmonster/steamcmd:ubuntu --tag nwsmonster/steamcmd:latest --label "version=$version_label" --label "github.ref=$GITHUB_REF" --label "github.runid=$GITHUB_RUN_ID" "$GITHUB_WORKSPACE"
      - name: "Test images"
        id: test-docker-images
        run: |
          docker run --rm nwsmonster/steamcmd:latest
      - name: "Publish images"
        id: publish-docker-images
        run: |
          docker push nwsmonster/steamcmd:latest
          docker push nwsmonster/steamcmd:ubuntu
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Build and publish latest images"
